version: '3.8'
services:
  lab_03:
    tty: true
    container_name: lab_03
    volumes:
      - .:/opt/arch
    build:
      context: ..
      dockerfile: Lab_3/Dockerfile #.devcontainer/Dockerfile
    environment:
      DB_HOST: lab03_postgres
      DB_PORT: 5432
      DB_LOGIN: root
      DB_PASSWORD: root
      DB_DATABASE: archdb
      MONGO_HOST: lab03_mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: arch
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - lab03-network
  db:
    container_name: lab03_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
      POSTGRES_DB: archdb
    volumes:
      - lab03_db:/data/postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - lab03-network
  mongodb:
    image: mongo:5.0
    container_name: lab03_mongo
    restart: on-failure
    networks:
      - lab03-network
    volumes:
      - lab03_mongodbdata:/data/db
    ports:
      - '27017:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

volumes:
  lab03_db:
  lab03_mongodbdata:


networks:
  lab03-network:
    driver: bridge
    external: false